SEED: 7
DEBUG: False
OUTPUT_BASE_DIR: '/storage/shafner/spacenet7/networks'
SAVE_CHECKPOINTS: [0, 25, 50, 75, 100]
THRESH: -1

MODEL:
  TYPE: 'unet'
  OUT_CHANNELS: 1
  IN_CHANNELS: 3
  LOSS_TYPE: 'JaccardLikeLoss'
  POSITIVE_WEIGHT: 250
  NEGATIVE_WEIGHT: 1
  TOPOLOGY: [64, 128, 256, 512,]
  BACKBONE:
    ENABLED: True
    TYPE: 'timm-efficientnet-b4'
    PRETRAINED_WEIGHTS: 'imagenet'

DATALOADER:
  NUM_WORKER: 16
  SHUFFLE: True
  LABEL: 'buildings'
  INCLUDE_ALPHA: False
  UPSAMPLE: 2
  IMAGE_STACK_OFFSETS: [0]

DATASETS:
  PATH: '/storage/shafner/spacenet7/'

TRAINER:
  BATCH_SIZE: 4
  EPOCHS: 101
  ALGORITHM: 'adamw'
  LR_SCHEDULE: 'cosine_anneal'
  LR: 5e-4
  T_0: 2100
  T_MULT: 2
  WEIGHT_DECAY: 0.0005

AUGMENTATION:
  CROP_SIZE: 512
  IMPORTANCE_CROPPING: False
  RANDOM_FLIP: True
  RANDOM_ROTATE: True
  PAD_TO_EVEN: True
  NORMALIZE_IMAGENET: False
  HISTOGRAM_EQUALIZATION: False
  COLORS: False
