_BASE_: "base.yaml"
DEBUG: True

TRAINER:
  BATCH_SIZE: 2

MODEL:
  TYPE: 'dtsiameseunet'
  ENABLE_SEMANTIC_CHANGE_LOSS: True

DATALOADER:
  INCLUDE_BUILDING_LABELS: True
  INCLUDE_UNLABELED: True

CONSISTENCY_TRAINER:
  LOSS_FACTOR: 0.1
  LOSS_TYPE: 'PowerJaccardLoss'