_BASE_: "base.yaml"
DEBUG: False
INFERENCE_CHECKPOINT: 100

MODEL:
  TYPE: 'dtsiameseunet'
  BATCH_SIZE: 16

DATALOADER:
  INCLUDE_BUILDING_LABELS: True

AUGMENTATION:
  IMAGE_OVERSAMPLING_TYPE: 'none'