_BASE_: "regional_split.yaml"
DEBUG: False

MODEL:
  TYPE: 'dtsiameseunet'
  ENABLE_SEMANTIC_CHANGE_LOSS: True

DATALOADER:
  INCLUDE_BUILDING_LABELS: True
  INCLUDE_UNLABELED_VALIDATION: True
  INCLUDE_UNLABELED_TEST: True


