_BASE_: "base.yaml"
DEBUG: False

MODEL:
  TYPE: 'dtsiameseunet'
  ENABLE_SEMANTIC_CHANGE_LOSS: True

DATALOADER:
  INCLUDE_BUILDING_LABELS: True
  INCLUDE_UNLABELED: True

CONSISTENCY_TRAINER:
  ENABLE_SUPERVISED_PRETRAINING: True
  EPOCHS_PRETRAINING: 1
  LOSS_FACTOR: 0.1
  LOSS_TYPE: 'PowerJaccardLoss'