_BASE_: "base_t50.yaml"
DEBUG: False
GROUP: 'dtsiamese_benchmark_cons10_t50'

MODEL:
  TYPE: 'dtsiameseunet'
  ENABLE_SEMANTIC_CHANGE_LOSS: False
  ENABLE_SEMANTIC_CHANGE_OUTCONV: False

DATALOADER:
  INCLUDE_BUILDING_LABELS: True
  INCLUDE_UNLABELED: True

CONSISTENCY_TRAINER:
  LOSS_FACTOR: 1.0
  LOSS_TYPE: 'PowerJaccardLoss'