_BASE_: "regional_split.yaml"
DEBUG: False
INFERENCE_CHECKPOINT: 100

MODEL:
  TYPE: 'dtsiameseunet'

DATALOADER:
  INCLUDE_BUILDING_LABELS: True
  INCLUDE_UNLABELED: True

AUGMENTATION:
  CROP_SIZE: 256

CONSISTENCY_TRAINER:
  LOSS_FACTOR: 0.1
  LOSS_TYPE: 'PowerJaccardLoss'