_BASE_: "base_t50.yaml"
DEBUG: False

LOGGING:
  GROUP: 'dtsiamese_benchmark_t50'

MODEL:
  TYPE: 'dtsiameseunet'
  ENABLE_SEMANTIC_CHANGE_LOSS: False
  ENABLE_SEMANTIC_CHANGE_OUTCONV: False

DATALOADER:
  INCLUDE_BUILDING_LABELS: True
  INCLUDE_UNLABELED: True

CONSISTENCY_TRAINER:
  LOSS_FACTOR: 0.1
  LOSS_TYPE: 'PowerJaccardLoss'