_BASE_: "base.yaml"
DEBUG: False

MODEL:
  TYPE: 'dtsiameseunet'
  IN_CHANNELS: 4
  ENABLE_SEMANTIC_CHANGE_LOSS: True

DATALOADER:
  SENSOR: 'sentinel2'
  INCLUDE_BUILDING_LABELS: True
  INCLUDE_UNLABELED: True

CONSISTENCY_TRAINER:
  LOSS_FACTOR: 0.5
  LOSS_TYPE: 'PowerJaccardLoss'