_BASE_: "base.yaml"
DEBUG: False

MODEL:
  TYPE: 'dtsiameseunet'

DATALOADER:
  INCLUDE_BUILDING_LABELS: True
  INCLUDE_UNLABELED_VALIDATION: True
  INCLUDE_UNLABELED_TEST: True


CONSISTENCY_TRAINER:
  LOSS_FACTOR: 0.1
  LOSS_TYPE: 'L2'