_BASE_: "regional_split.yaml"
DEBUG: False

MODEL:
  TYPE: 'dtsiameseunet'

DATALOADER:
  INCLUDE_BUILDING_LABELS: True
  INCLUDE_UNLABELED_VALIDATION: True
  INCLUDE_UNLABELED_TEST: True


AUGMENTATION:
  GAMMA_CORRECTION: True
