_BASE_: "regional_split.yaml"
DEBUG: False
INFERENCE_CHECKPOINT: 100

MODEL:
  TYPE: 'dtsiameseunet'

DATALOADER:
  INCLUDE_BUILDING_LABELS: True
  INCLUDE_UNLABELED: True

CONSISTENCY_TRAINER:
  LOSS_FACTOR: 0.1
  WEIGHT_DECAY: 0.998
  APPLY_THRESHOLD: False
  LOSS_TYPE: 'L2'
