_BASE_: "regional_split.yaml"
DEBUG: False
INFERENCE_CHECKPOINT: 20

MODEL:
  TYPE: 'dtsiameseunet'
  TOPOLOGY: [64, 128, 256, 512,]

DATALOADER:
  INCLUDE_BUILDING_LABELS: True
  INCLUDE_UNLABELED: True

AUGMENTATION:
  GAMMA_CORRECTION: True
