_BASE_: "base2.yaml"

MODEL:
    TOPOLOGY: [16, 32, 64, 128, ]

DATALOADER:
    UPSAMPLE: 2

AUGMENTATION:
  CROP_SIZE: 1024

TRAINER:
  LR_SCHEDULE: 'cosine_anneal'
  LR: 5e-3
  T_0: 2000
  T_MULT: 2
